# Default target
.PHONY: all
# all: slither

# Target to run Slither
.PHONY: slither
slither:
	slither src/ 

slitherin:
	slitherin src/ --pess

aderyn:
	aderyn .

myth:
	myth analyze src/Counter.sol:Counter

